# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: publish

on:
  release:
    types:
      - created

jobs:
  sdist:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Setup python3.9
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install poetry
        run: python -m pip install poetry

      - name: Publishing to pypi
        run: poetry publish --build
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_TOKEN }}

  image:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Read Poetry TOML
        uses: SebRollen/toml-action@v1.0.2
        id: read_toml
        with:
          file: 'pyproject.toml'
          field: 'tool.poetry.version'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ steps.read_toml.outputs.value }}
            ghcr.io/${{ github.repository }}:latest
