# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: publish

on:
  release:
    types:
      - created

jobs:
  sdist:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Setup python3.9
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install requires
        run: python -m pip install twine wheel

      - name: Build source package
        run: python setup.py sdist

      - name: Publishing to pypi
        run: twine upload --skip-existing --disable-progress-bar dist/*.tar.gz
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
